### ISSUE TITLE
Creating SQLite in memory fails

### ISSUE THREAD

**Issue by MarcinOrlowski** [cakephp/phinx#1116]
Attempt to create SQLIte database in memory as documented in docs, i.e.

```
environments:
    testing:
        adapter: sqlite
        memory: true     # Setting memory to *any* value overrides name
```

fails:

```
$ vendor/bin/phinx migrate -e testing
Phinx by Rob Morgan - https://phinx.org. 0.8.1

using config file ./phinx.yml
using config parser yaml
using migration paths 
 - /<redacted>/db/migrations
using seed paths 
 - /<redacted>/db/seeds
using environment testing
using adapter sqlite
Could not determine database name! Please specify a database name in your config file.
```

The workaround for this is to provide `name` regardless it is used or not:

```
environments:
    testing:
        adapter: sqlite
        name: /tmp/db
        memory: true
```
