### ISSUE TITLE
Problem with pdo_mysql connection using PHINX

### ISSUE THREAD

**Issue by jopsilva** [cakephp/phinx#1302]
When trying to execute the migration `vendor/bin/phinx migrate` to MySQL, I am receiving this ...

## > " There was a problem connecting to the database: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name or service not  
   known . "
```yaml
### docker-compose.yml
version: "3" 
services:
  .# Web service layer
  nginx:
    image: nginx:1.13
    volumes:
      - "./app:/var/www/html"
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
    ports:
      - "80:80"
    depends_on:
      - php

  .# Application service layer
  php:
    build:
      context: ./php
    volumes:
      - "./app:/var/www/html"
    ports:
      - "9000:9000"
    depends_on:
      - mysql
    environment:
      - MYSQL_USER=root
      - MYSQL_PASS=root
  
  .# Data persistence service layer
  mysql:
    image: mysql:5.7.20
    volumes:
      - "db_data:/var/lib/mysql"
      - "./mysql/initial_data:/docker-entrypoint-initdb.d"
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root

volumes:
  db_data:
```
```dockerfile
### Dockerfile PHP
FROM php:7.2-fpm
RUN docker-php-ext-install mysqli pdo_mysql
```
> project link

https://github.com/jopsilva/docker-nginx-php-pfm-mysql
