### ISSUE TITLE
Migration issue with v0.9.2

### ISSUE THREAD

**Issue by chinenyeze** [cakephp/phinx#1321]
I noticed the following error in the latest version (0.9.2), which seems to not occur in the previous version (0.9.1).

When I run `bin/phinx create InitialSetup` it gives the error:

```
In Inline.php line 296:
                                                                                                                                                           
  The reserved indicator "%" cannot start a plain scalar; you need to quote the scalar at line 2 (near "migrations: %%PHINX_CONFIG_DIR%%/db/migrations").  
                                                                                                                                                           
```

In my `phinx.yml` I make use of the config placeholder, i.e. `%%PHINX_CONFIG_DIR%%`. Below is my `phinx.yml`.

```
paths:
    migrations: %%PHINX_CONFIG_DIR%%/db/migrations
    seeds: %%PHINX_CONFIG_DIR%%/db/seeds

environments:
    default_migration_table: phinxlog
    default_database: development

    development:
        adapter: mysql
        host: 127.0.0.1
        name: stuff
        user: stuff
        pass: 'stuff'
        port: 3306
        charset: utf8

version_order: creation
```

So this is an issue with the new phinx 0.9.2 version, pls rectify. Thanks.
