### ISSUE TITLE
PDOException: SQLSTATE[42P01]: Undefined table: 7 ERROR:  relation "phinxlog" does not exist

### ISSUE THREAD

**Issue by mpjraaij** [cakephp/phinx#1713]
Hi there,

My yml file looks like this:
```
paths:
  migrations: /app/code/migrations
environments:
  default_migration_table: phinxlog
  default_database: develop
  develop:
    adapter: pgsql
    host: ...
    name: develop
    user: ...
    pass: ...
    port: 5432
```

When I run the code I get the error that the relation for "phinxlog" does not exist. How can I solve this?

Thank you so much!
