### ISSUE TITLE
Oracle suport

### ISSUE THREAD

**Issue by alphabraga** [cakephp/phinx#215]
Hi!

I would love to see this tool talking to Oracle. Knowing PHP PDO for Oracle is experimental. I suggest using the OCI. 

Reading other issues I realized that we need a VM to run unit tests for Oracle, I have one with Ubuntu and Oracle XE up and running ....

**Comment by davide-romanini** [comment]
Perhaps there's some chance to run it on travis: https://github.com/cbandy/travis-oracle. It needs a valid oracle account though, but theoretically it should be possible.

**Comment by skie** [comment]
What is the plan about implementation of Oracle OCI8 driver?

**Comment by mjanda** [comment]
I'm starting to work on Oracle OCI8 version here https://github.com/mjanda/phinx

So far, `status`, `create`, and `migrate` work for pure SQL migrations which is more or less what we need. If you need more functionality, feel free to contribute. I'll probably implement some other checking methods (hasTable, hasColumn etc...) but I won't be doing full implementation of table creation / modification methods.

And I'll let @robmorgan decide if he wants such bare implementation in phinx or if only fully implemented adapters should be merged in.

phinx.yml looks like this:
```yml
paths:
    migrations: %%PHINX_CONFIG_DIR%%/db/migrations_oracle
    seeds: %%PHINX_CONFIG_DIR%%/db/seeds_oracle

environments:
    default_migration_table: PHINXLOG_ORACLE
    default_database: development

    development:
        adapter: oracle
        host: 127.0.0.1
        sid: XE
        name: SYSTEM
        user: system
        pass: manager
        port: 1521
        charset: utf8
```

Known problems

- datetime in status list is wrong...not sure why
- there is an ugly hack for lowercasing array keys in `getVersionLog`
- and of couse, it extends PdoAdapter while not being PDO based...well...
