### ISSUE TITLE
Setting default_migration_table is ignored and phinxlog table is used anyway.

### ISSUE THREAD

**Issue by StenAkeStrid** [cakephp/phinx#53]
I expected that setting `default_migration_table` would change what the database table is called in the database.  That did not happen for me. After changing this setting in phinx.yml to `version` and then running my first migration, the migration info was still stored in a new table `phinxlog`, apparantly using the old value. 

Part of my phinx.yml (anonymized)

```
paths:
    migrations: %%PHINX_CONFIG_DIR%%/../../../migrations

environments:
    default_migration_table: version
    default_database: development
    development:
        adapter: mysql
        host: localhost
        name: dev
        user: changetoyouruserhere
        pass: 'changetoyourpasswordhere'
        port: 3306
```

If it matters my setup looks like this: MySQL 5.5.16, PHP 5.4.3 on Windows 7. Not using Symfony for anything else. My migrations runs just fine otherwise.
