### ISSUE TITLE
UTF8 in execute block get corrupted

### ISSUE THREAD

**Issue by djpate** [cakephp/phinx#63]
Hello,

When I use execute with some special characters (accent and such) they get corrupted. Not sure how to fix that.

Thanks,

**Comment by gwagroves** [comment]
@robmorgan Is UTF8 still forced for MySQL, or does it have to be explicitly declared in the config?

**Comment by lherich** [comment]
@gwagroves You need to define the charset/collation within the configuration.

---

Example
```yml
environments:
    default_migration_table: phinxlog
    default_database: development
    production:
        adapter: mysql
        host: localhost
        name: production_db
        user: root
        pass: ''
        port: 3306
        charset: utf8
        collation: utf8_unicode_ci
```
[See documentation (section Configuration/Environments)](http://docs.phinx.org/en/latest/configuration.html?highlight=utf8#environments)
