### ISSUE TITLE
MySQL DSN Configuration

### ISSUE THREAD

**Issue by bradynpoulsen** [cakephp/phinx#646]
I'm trying to get my application ready for backwards compatability and noticed that the configuration provides no option to allow you to specify the dsn yourself. I can see you can provide `adapter, host, name, user, pass, port, and charset`; however, I have an environment variable `MYDB_DNS`, etc that I would like to import into my yaml file.

I would like to instead define

``` yaml
environments:
    production:
        adapter: mysql
        dsn: %%ENV_MYDB_DSN%%
    development:
        adapter: mysql
        dns: mysql://user:password@localhost/database_name
```
