### ISSUE TITLE
phinxlog table in schema fails

### ISSUE THREAD

**Issue by tpetry** [cakephp/phinx#915]
If you define your postgresql configuration with a schema [1] the `phinx --migrate` will correctly create the phinxlog table in this schema (`appschema.phinxlog`) but then fails to read it, exiting with the following error:

```
[PDOException (42P01)]                                                          
  SQLSTATE[42P01]: Undefined table: 7 ERROR:  relation "phinxlog" does not exist  
  LINE 1: SELECT * FROM phinxlog ORDER BY version ASC                             
                        ^                                                         


Exception trace:
 () at /Users/tpetry/www/someapp/webapp/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/PdoAdapter.php:346
 PDO->query() at /Users/tpetry/www/someapp/webapp/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/PdoAdapter.php:346
 Phinx\Db\Adapter\PdoAdapter->query() at /Users/tpetry/www/someapp/webapp/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/PdoAdapter.php:364
 Phinx\Db\Adapter\PdoAdapter->fetchAll() at /Users/tpetry/www/someapp/webapp/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/PdoAdapter.php:409
 Phinx\Db\Adapter\PdoAdapter->getVersionLog() at /Users/tpetry/www/someapp/webapp/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/PdoAdapter.php:398
 Phinx\Db\Adapter\PdoAdapter->getVersions() at /Users/tpetry/www/someapp/webapp/vendor/robmorgan/phinx/src/Phinx/Migration/Manager/Environment.php:230
 Phinx\Migration\Manager\Environment->getVersions() at /Users/tpetry/www/someapp/webapp/vendor/robmorgan/phinx/src/Phinx/Migration/Manager.php:260
 Phinx\Migration\Manager->migrate() at /Users/tpetry/www/someapp/webapp/vendor/robmorgan/phinx/src/Phinx/Console/Command/Migrate.php:113
 Phinx\Console\Command\Migrate->execute() at /Users/tpetry/www/someapp/webapp/vendor/symfony/console/Command/Command.php:256
 Symfony\Component\Console\Command\Command->run() at /Users/tpetry/www/someapp/webapp/vendor/symfony/console/Application.php:815
 Symfony\Component\Console\Application->doRunCommand() at /Users/tpetry/www/someapp/webapp/vendor/symfony/console/Application.php:186
 Symfony\Component\Console\Application->doRun() at /Users/tpetry/www/someapp/webapp/vendor/robmorgan/phinx/src/Phinx/Console/PhinxApplication.php:83
 Phinx\Console\PhinxApplication->doRun() at /Users/tpetry/www/someapp/webapp/vendor/symfony/console/Application.php:117
 Symfony\Component\Console\Application->run() at /Users/tpetry/www/someapp/webapp/vendor/robmorgan/phinx/bin/phinx:28
```

---

[1] example config

``` yaml
environments:
    default_migration_table: phinxlog
    default_database: postgresql
    postgresql:
        adapter: pgsql
        host: localhost
        port: 5432
        user: "myuser"
        pass: "mypassword"
        name: "mydatabase"
        charset: utf8
        schema: "appschema"
```
